### PR TITLE
HACS install

### PR DESCRIPTION
**Pull request by anthonyangel**
Allow installing via HACS, setup according to https://hacs.xyz/docs/publish/integration

### CODE REVIEW

**Comment by markgdev** [comment]
This is awesome! Thanks so much! Sorry it took me so long to merge the request I wanted to try and test it with HACS but have failed miserably, I think because it's not on the default branch so going to merge and then try again. I can see that nothing should break though, I just need to update the readme with the new dir details.

**Comment by anthonyangel** [comment]
No problem, I've swapped my custom repo in hacs to use your repo and it works.

The docs to install it as a default hacs repository instead of a custom one are at https://hacs.xyz/docs/publish/include if you wanted (it says that the repo owner has to submit it, so I'm not planning on doing anything here)

**Comment by markgdev** [comment]
Did you have any issues with the camel case naming? The directory got created as octopusagile, however the config looks for OctopusAgile so it fails, I updated manifest.json to camel case and that fixes the directory naming but I'm about to go down a rabbit hole of finding all the references to the lower case name and I think that might cause people issues with their sensor names if they're used in automations.

**Comment by anthonyangel** [comment]
I have the following structure inside `custom_components:`
```
octopusagile
 |
 +-- __init.py__
 +-- config_flow.py
 +-- const.py
 +-- manifest.json
 +-- sensor.py
 +-- strings.json
 +-- OctopusAgile/
    |  
    +-- Agile.py
    +-- __init.py__
```

It seems to work fine

**Comment by markgdev** [comment]
I'm probably doing something stupid. I get "2020-11-29 21:21:50 ERROR (MainThread) [homeassistant.setup] Setup failed for OctopusAgile: Integration not found."

In your configuration.yml are you using camel case or all lower case?

**Comment by anthonyangel** [comment]
I get that log message too, I'm using camelcase in my configuration.yaml

The rates update as normal, I'm not actually using the timers or devices yet (I'm on Octopus Go at the moment and working out the maths on moving to Agile, but wanted to test this before switching over) - it looks like it's still working as it should be

**Comment by markgdev** [comment]
Cool, that makes sense. I will work through and fix the issue I'm having now I know it's not something I'm doing wrong!

Thanks again for doing this, I will try and add it as a default HACS repo once I have it working properly.

**Pull request merged**
