### PR TITLE
Added new avg rate sensors

### PR DESCRIPTION
**Pull request by markgdev**

### CODE REVIEW

**Comment by GGW42** [comment]
hi @markgdev Thank you for taking the time to write this code, I joined Octopus last November and I hope you liked the little present as I used your referral code when I did. This is my first message to your page as I am still learning Home Assistant and your Octopus Agile custom component. 
I was interested in adding these average rates sensors to HA as a graph but can't find them, they seem to be in the code as 
"octopusagile.avg_rate_exc_peak" & "octopusagile.avg_rate_inc_peak" but I can't find and entiry with these names. I am using your latest code?

**Comment by markgdev** [comment]
Hi @GGW42, thanks for using the referral code, it does help keep me motivated! I think you might have the average sensors now, they get updated at 1900 each day along with the timers. I need to work out the best way to populate them if you add them before the next days rates are available but haven't come up with a good solution yet. If the rates are available you can call the octopusagile.updates_timers service to force update them earlier.
You might also notice that at the moment they don't repopulate automatically after a home assistant restart. I'm going to open an issue for this and get that fixed.

**Comment by GGW42** [comment]
@markgdev you are correct. They did show up but even though they are a number I can't graph them. I assume that means they are stored as text so I will need to work out how to convert them.
image
Is that why they aren't sensors? The sensors are all numbers and will show on a graph? I can understand why Timer and rates are stored as lists but < sensor.octopus_agile_current_rate > is stored as a number with units so shouldn't <octopusagile.avg_rate_exc_peak> & <octopusagile.avg_rate_inc_peak>  be stored the same way or is there a particular reason they are stored as they are? I am still learning this, just trying to work out some of the logic for why you have organised things as you have.

**Comment by markgdev** [comment]
The reason I didn't name them as sensors is honestly because of where I copied the code from to create them! Somebody else asked me the same question and I completely agree that it would be more logical to have named them in the sensor domain. so I am going to rename them to sensor.avg*.

The reason for the lack of graph I think is because I haven't added a unit of measurement, which was a bit of an oversight, I'll add that in too.

I'm intrigued how you have different values for the entities in the history already, or did you just overwrite them manually?

**Comment by GGW42** [comment]
No, I had been running your latest code for some time, it just happened when i got to looking at this part of it, it was after I had rebooted for another reason and thus couldn't see the items until I forced an update via <octopusagile.updates_timers> service, so the values would have been in History, had i thought to look there.

**Pull request merged**
