### PR TITLE
updated for use with input_boolean also

### LINKED ISSUE #28: Add output boolean device for each timer to trigger automations
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
When an octopusagile.timers time period becomes active (on), set a boolean (like input_boolean) that can be used to trigger an automation. The boolean should become inactive (off) when the timer is no longer triggered. Each boolean output would be named using a timer "name" attribute.

**Describe alternatives you've considered**
The following snippet doesn't appear to work (log: helper fails to find entity):
  timers:
  - day_from: tomorrow
    day_to: tomorrow
    entity_id: input_boolean.immersion_request

**Additional context**
The idea is to find the cheapest time(s) to turn on a device, but with the ability to override with automation conditions. E.g. turn on immersion heater at cheapest time(s), but only if current price < 3p and "holiday mode" input_boolean is false. If the immersion doesn't come on, I have gas as a backup.

### PR DESCRIPTION
**Pull request by daaaaan**
A fix to use with input_booleans also. 

I'm not great with python. For a start there's no case statement. So enjoy my nested ifs. It was a copy paste hack job. 

@markgdev might want to review. 

But this might fix #28

### CODE REVIEW

**Comment by daaaaan** [comment]
I didn't actually test, something wrong, prevents startup of HA, most likely my syntax is way off. 

PS did I mention me < python.

**Comment by nick-ratbert** [comment]
Hi Daaaaan,

Thanks for looking at this. I have not tried it myself yet, but reading the diff seems to show that this line:

hass.services.call('switch', 'turn_off', {'entity_id': entity_id})

is not indented correctly after the final else: in your diff, around lines 255/256.

As Python is indent sensitive, I wonder if that is the source of the startup problem.

**Comment by nick-ratbert** [comment]
Daaaaan,

I cut and pasted your diff and added four spaces as I suggested. My input_boolean (manually turned on) correctly turned off on the next half hour interval. It's not due to turn on until the wee hours, but I expect it is going to work.

Thanks again!

**Comment by nick-ratbert** [comment]
After 0.116 logging was fixed, the input_boolean behaved exactly as expected. Works great for me.

**Review by markgdev — COMMENTED** [review]
@daaaaan looks great, did you want to sort the indent and reopen the pull request and I'll get it added in?

**Pull request closed without merging**
